const egyptianCities = [
  { index: 1, value: "Cairo" },
  { index: 2, value: "Alexandria" },
  { index: 3, value: "Giza" },
  { index: 4, value: "Shubra El Kheima" },
  { index: 5, value: "Port Said" },
  { index: 6, value: "Suez" },
  { index: 7, value: "Luxor" },
  { index: 8, value: "Asyut" },
  { index: 9, value: "Mansoura" },
  { index: 10, value: "Tanta" },
  { index: 11, value: "Mahalla El Kubra" },
  { index: 12, value: "Zagazig" },
  { index: 13, value: "Ismailia" },
  { index: 14, value: "Faiyum" },
  { index: 15, value: "Damietta" },
  { index: 16, value: "Aswan" },
  { index: 17, value: "Minya" },
  { index: 18, value: "Damanhur" },
  { index: 19, value: "Beni Suef" },
  { index: 20, value: "Qena" },
  { index: 21, value: "Sohag" },
  { index: 22, value: "Hurghada" },
  { index: 23, value: "Qalyub" },
  { index: 24, value: "Banha" },
  { index: 25, value: "Arish" },
  { index: 26, value: "Mallawi" },
  { index: 27, value: "Bilbeis" },
  { index: 28, value: "Marsa Matruh" },
  { index: 29, value: "Badr" },
  { index: 30, value: "Belqas" },
  { index: 31, value: "Salhiya" },
  { index: 32, value: "Sheikh Zuweid" },
  { index: 33, value: "Shibin El Kom" },
  { index: 34, value: "Toukh" },
  { index: 35, value: "Madinat Sittah Uktubar" },
  { index: 36, value: "New Cairo" },
  { index: 37, value: "Borg El Arab" },
  { index: 38, value: "Obour City" },
  { index: 39, value: "New Damietta" },
  { index: 40, value: "El Shorouk" },
];

export default egyptianCities;
